services:
  nginx:
    image: nginx:alpine
    hostname: rinha-nginx
    restart: unless-stopped
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend-api-1
      - backend-api-2
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: "20MB"

  backend-api-1: &api
    build: .
    hostname: rinha-backend-api-1
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - backend
      - payment-processor
    expose:
      - "9999"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "60MB"

  backend-api-2:
    <<: *api
    hostname: rinha-backend-api-2

  workers:
    build: .
    hostname: rinha-workers
    command: ["python", "-m", "app.queue"]
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: "130MB"

  redis:
    image: redis:8.2.0-alpine
    hostname: rinha-redis
    restart: unless-stopped
    command: [
      "redis-server", "--save", "--appendonly", "no", "--maxclients", "5000"
    ]
    ports:
      - "6379:6379"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "80MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
